spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-rds-itsum.cqehgizaa4nn.ap-northeast-2.rds.amazonaws.com:3306/itsum
    username: admin
    password: 1234567890

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8a7f95d051ea6cd60d81cb925bdce26a
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
          google:
            clientId: 135985880546-0p76g773d2ctglkjtlr6gb8034uk9mln.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "http://localhost:8080/login/oauth2/code/google"
            scope: profile,email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpiry: 86400000
